catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('create_book/', views.BookCreate.as_view(), name='create_book'),
    path('book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
    path('my_view/', views.my_view, name='my_view'),
    path('profile/', views.CheckedOutBooksByUserView.as_view(), name='profile'),
    path('list_books/', views.ListAllBooks.as_view(), name="list_books")
]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/')),
    path('accounts/', include('django.contrib.auth.urls'))
]

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User


class Genre(models.Model):

    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Book(models.Model):

    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=600)
    isbn = models.CharField('ISBN', max_length=13, unique=True)
    genre = models.ManyToManyField(Genre)
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.title}"

    def get_absolute_url(self):
        return reverse('book_detail', kwargs={'pk': self.pk})


class Author(models.Model):

    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    date_of_birth = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('author_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return f"{self.last_name}, {self.first_name}"


class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On Loan'),
        ('a', 'Available'),
        ('r', 'Reserved')
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m')

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        return f'{self.id} {self.book.title}'

catalog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models
from django.views.generic import CreateView, DetailView, ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


def index(request):
    num_books = models.Book.objects.all().count()
    num_instances = models.BookInstance.objects.all().count()
    num_instances_avail = models.BookInstance.objects.filter(status__exact='a').count()

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_avail': num_instances_avail
    }

    return render(request, 'catalog/index.html', context=context)

class ListAllBooks(ListView, LoginRequiredMixin):
    model = models.Book
    fields="__all__"
    template_name = "book_list.html"


class BookCreate(LoginRequiredMixin, CreateView):
    model = models.Book
    fields = '__all__'

class BookDetail(DetailView):
    model = models.Book

@login_required
def my_view(request):
    return render(request, 'catalog/my_view.html')

class CheckedOutBooksByUserView(LoginRequiredMixin, ListView):
    model = models.BookInstance
    template_name = 'catalog/profile.html'
    paginate_by = 10

    def get_queryset(self):
        return models.BookInstance.objects.filter(borrower=self.request.user).all()

catalog/templates/catalog/book_detail.html
<h1>Detail for Book</h1>
{{book}}

catalog/templates/catalog/book_form.html
<h1>Create New Book</h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="CREATE">
</form>

catalog/templates/catalog/book_list.html
<h1>List all books</h1>
<br>
{% for book in book_list %}
    <p>{{book.id}} | {{book.title}} | {{book.author}} | {{book.genre}}</p>
{% endfor %}

catalog/templates/catalog/index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>HOME PAGE</h1>
    <p>Total Books: {{num_books}}</p>
    <p>Num Available: {{num_instances_avail}}</p>
    {% if user.is_authenticated %}
        <p>You are logged in</p>
        <p>Welcome: {{user.get_username}}</p>
        <a href="{% url 'logout' %}?next={{request.path}}">Log out</a>
    {% else %}
        <p>You are not logged in.</p>
        <a href="{% url 'login' %}?next={{request.path}}">Log in</a>
    {% endif %}
</body>
</html>

catalog/templates/catalog/my_view.html
<p>Logged in users only</p>

catalog/templates/catalog/profile.html
<h1>Welcome to your profile, {{user}}</h1>
<h2>Here are your books checked out:</h2>

{% for book in bookinstance_list %}
    <p>{{book}}</p>
{% endfor %}